server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost/mydatabase?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 13152130059myz
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false

  mvc:
    static-path-pattern: /static/**
