server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost/mydatabase?characterEncoding=utf8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 13152130059myz
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  mvc:
    pathmatch:
      use-suffix-pattern: true


